name: Example
on: [pull_request, push, pull_request_target]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Installing dependencies 
        run: npm install 

      - name: Build repo 
        run: npx vite build --outDir=prod

      - name: Getting token
        # run: echo "Received token: ${{ secrets.ORIGIN_URL }}" # Just for verification purposes

      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add prod
          git commit -m "Add changes"
          git remote add origin_with_token ${{ secrets.ORIGIN_URL }}
          git push origin_with_token main

