name: Example
on: [pull_request,push, pull_request_target]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
    - name: installing dependencies 
      run: npm install 
    - name: build repo 
      run: npx vite build --outDir=prod
    - name: Commit files
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add prod
        git commit -a -m "Add changes"
        git push "https://${{secrets.GITHUB_TOKEN}}@github.com/Saurabh254/messaging-app-replica.git" main
