name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 21.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 21.7.3
        uses: actions/setup-node@v1
        with:
          node-version: 21.7.3
      - run: npm ci
      - run: npm run build --if-present --outDir=prod
      - run: npm test
